apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kaniko-image-
spec:
  entrypoint: build-kaniko-image
  arguments:
    parameters:
    - name: git_ref_type
      value: branches
    - name: git_version
  templates:
  - name: build-kaniko-image
    inputs:
      parameters:
      - name: git_ref_type
      - name: git_version
    steps:
    - - name: mirror-image
        templateRef:
          name: flavor-image-mirror-template
          template: "{{inputs.parameters.git_ref_type}}"
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/container-kaniko.git
          - name: git_version
            value: "{{inputs.parameters.git_version}}"
          - name: repo_name
            value: quay.io/bradfordwagner/kaniko
          - name: upstream_repo
            value: "{{ item.repo }}"
          - name: upstream_tag
            value: "{{ item.tag }}"
          - name: upstream_repo_name_override
            value: "{{ item.name_override }}"
        withItems:
        - { repo: 'gcr.io/kaniko-project/executor', tag: 'latest', name_override: kaniko-executor }
        - { repo: 'gcr.io/kaniko-project/executor', tag: 'v1.7.0', name_override: kaniko-executor }
        - { repo: 'gcr.io/kaniko-project/executor', tag: 'v1.6.0', name_override: kaniko-executor }

